// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp( 
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Rvf0B-GktyyPzlMaRjCW386zjsEPMoM',
    appId: '1:429689949388:web:3b6795956a41039e808669',
    messagingSenderId: '429689949388',
    projectId: 'crud-e2ab3',
    authDomain: 'crud-e2ab3.firebaseapp.com',
    storageBucket: 'crud-e2ab3.appspot.com',
    measurementId: 'G-0YZXQMPCC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdKUpT9L0tD2dbzf2GBQA2wKOpXajigUY',
    appId: '1:429689949388:android:2c76c9508e5951e4808669',
    messagingSenderId: '429689949388',
    projectId: 'crud-e2ab3',
    storageBucket: 'crud-e2ab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy4KSEdrCN8IF7iVdmAx7jXQbyKHmLCoY',
    appId: '1:429689949388:ios:dff57ce1279f8670808669',
    messagingSenderId: '429689949388',
    projectId: 'crud-e2ab3',
    storageBucket: 'crud-e2ab3.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy4KSEdrCN8IF7iVdmAx7jXQbyKHmLCoY',
    appId: '1:429689949388:ios:dff57ce1279f8670808669',
    messagingSenderId: '429689949388',
    projectId: 'crud-e2ab3',
    storageBucket: 'crud-e2ab3.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Rvf0B-GktyyPzlMaRjCW386zjsEPMoM',
    appId: '1:429689949388:web:26dcb1137d082136808669',
    messagingSenderId: '429689949388',
    projectId: 'crud-e2ab3',
    authDomain: 'crud-e2ab3.firebaseapp.com',
    storageBucket: 'crud-e2ab3.appspot.com',
    measurementId: 'G-J3973NKYSQ',
  );
}
